image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
- build
- publish

variables: 
  Configuration: Release
  
build:
  stage: build
  script:
  - echo "$PWD/FaissMask/runtimes/linux-x64/native" > /etc/ld.so.conf.d/faissmask.conf
  - ldconfig
  - dotnet build
  - dotnet test FaissMask.Test
  artifacts:
    name: packages
    paths:
      - FaissMask/bin/$Configuration/*.nupkg

publish to nuget.org:
  stage: publish
  only:
  - master
  script:
  - dotnet nuget push $(ls FaissMask/bin/$Configuration/*.nupkg) -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json  
  environment:
    name: nuget.org
    url: https://nuget.org/packages/FaissMask/
  when: manual  
